### ISSUE TITLE
Not passing boolean flags to validators can beak custom validators in Sails models

### ISSUE THREAD

**Issue by lennym** [sailsjs/anchor#102]
Changing from 0.10.5 to 0.11.0 of anchor as a grandchild dependency of our sails app broke some of our custom async validator methods.

[Details](https://github.com/balderdashy/sails/issues/3463)

In particular [this commit](https://github.com/sailsjs/anchor/commit/9abea11ecf32ae935b3b9dcfae797492451aa2fb) means that our custom validator always fails, because the flag it exports is boolean, and the function we set to the types property in our model is expected a `true` flag.

**Comment by particlebanana** [comment]
The pretext for that change was that there is no reason to pass the flag turing the validation on/off to the actual validator. So if you have `email: true` the validator doesn't care about the boolean value. It will either run the validation if set to `true` or skip it if set to `false`. On the other hand if you have `len: { max: 4, min: 2 }` the validator does care about those options. Before this was causing issues as the flag value was being passed in as options to the validator.

I will add some documentation but in your case you want the second argument to be an options object. So changing the validation to the following should get you up and running.

Let me know if that doesn't work out for you.

```javascript
module.exports = {
  connection: 'mongo',
  tableName: 'applications',
  types: {
    asyncValidator: function (input, options) {
      var isUnique = options.isUnique || false;
      return isUnique;
    }
  },
  attributes: {
    name: {
      type: 'string',
      required: true,
      asyncValidator: function (callback) {
        Async.operation().then(function (rows) { callback({ isUnique: rows.length === 0 }); });
      }
    }
  }
};
```

**Comment by lennym** [comment]
Thanks. I knew I was using undocumented functionality, so I suppose I can't complain too much about it breaking under me ;-) It would probably be handy if this could be documented in future though.

I'd already fixed in our case by passing the numerical value to the callback, and then checking equality with 0 in the type method, but if passing an object is the "supported" approach then I'll convert to doing that.

Thanks again for your help.
